services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: HamRadioLogs
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  logging-api:
    build:
      context: .
      dockerfile: LoggingService/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  pgdata:
