global using System.Windows.Controls;
global using System.Windows;
global using LoggerWPF.Core;
global using Microsoft.Extensions.DependencyInjection;
global using HBWebLogger.Services.ApiClients;
global using Microsoft.Extensions.Hosting;
global using System.IO;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Options;
