global using System.Xml.Serialization;
global using HamBlocks.Library.Models.Lookup;
global using HBWebLogger.Areas.Identity;
global using HBWebLogger.Data;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using MudBlazor.Services;
